import numpy as np
import matplotlib.pyplot as plt

from etraj.etraj import Vector
from scipy.linalg import blas
import etraj.etraj as et

#  tests for vector class
print("\n-------Tests for Level 1 BLAS functions--------")
print("\n-----------------------------------------------")

print("\n(1) DSWAP")
print(">>> v = Vector('v',[1,2,3])")
print(">>> u = Vector('u',[3,2,1])")
print(">>> print(v)")
print(">>> print(u)")
print(">>> et.dswap(v,u)")
print(">>> print(v)")
print(">>> print(u)")
v = Vector('v',[1,2,3])
u = Vector('u',[3,2,1])
print(v)
print(u)
et.dswap(v,u)
print(v)
print(u)

print("\n(2) DSCAL")
print(">>> v = Vector('v',[1,2,3,4])")
print(">>> s = 5.3")
print(">>> print(v)")
print(">>> et.dscal(v,s)")
print(">>> print(v)")
v = Vector('v',[1,2,3,4])
s = 5.3
print(v)
et.dscal(v,s)
print(v)

print("\n(3a) DCOPY return vector")
print(">>> v = Vector('v',[1,0,9,3,4])")
print(">>> v_copy = et.dcopy(v)")
print(">>> print(v_copy)")
v = Vector('v',[1,0,9,3,4])
v_copy = et.dcopy(v)
print(v_copy)

print("\n(3a) DCOPY in place")
print(">>> v = Vector('v',[1,0,9,3,4])")
print(">>> u = Vector('u',[6,6,6,6,6])")
print(">>> print(v)")
print(">>> print(u)")
print(">>> et.dcopy(v,u)")
print(">>> print(u)")
v = Vector('v',[1,0,9,3,4])
u = Vector('u',[6,6,6,6,6])
print(v)
print(u)
et.dcopy(v,u)
print(u)

print("\n(4) DAXPY")
print(">>> v = Vector('v',[1,0,9,3,4])")
print(">>> u = Vector('u',[6,6,6,6,6])")
print(">>> s = 3.1")
print(">>> print(v)")
print(">>> print(u)")
print(">>> et.daxpy(v,s,u)")
print(">>> print(u)")
v = Vector('v',[1,0,9,3,4])
u = Vector('u',[6,6,6,6,6])
s = 3.1
print(v)
print(u)
et.daxpy(v,s,u)
print(u)

print("\n(5) DDOT")
print(">>> v = Vector('v',[1,0,9,3,4])")
print(">>> u = Vector('u',[6,6,6,6,6])")
print(">>> s = et.ddot(v,u)")
print(">>> print(s)")
v = Vector('v',[1,0,9,3,4])
u = Vector('u',[6,6,6,6,6])
s = et.ddot(v,u)
print(s)

print("\n(6) DNRM2")
print(">>> v = Vector('v',[1,2,3,4])")
print(">>> nrm = et.dnrm2(v)")
print(">>> print(nrm)")
v = Vector('v',[1,2,3,4])
nrm = et.dnrm2(v)
print(nrm)

print("\n(7) DASUM")
print(">>> v = Vector('v',[-1,2,-3,4])")
print(">>> vsum = et.dasum(v)")
print(">>> print(vsum)")
v = Vector('v',[-1,2,-3,4])
vsum = et.dasum(v)
print(vsum)

print("\n(8) IDAMAX")
print(">>> v = Vector('v',[9,7,5,2,0,53,6])")
print(">>> i = et.idamax(v)")
print(">>> print(i)")
v = Vector('v',[9,7,5,2,0,53,6])
i = et.idamax(v)
print(i)
